[package]
name = "osm_extract_polygon"
version = "0.1.41"
authors = ["Andreas <andreas.gemsa@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbfreader = "0.13.4"
clap = "2.33.1"

[build-dependencies]
protobuf-codegen-pure = "2"
