[package]
name = "osm_extract_polygon"
version = "0.3.1"
authors = ["Andreas <andreas.gemsa@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
geojson = { version =  "0.22.0", features=["geo-types"] }
geo-types = "0.7.0"
osmpbfreader = "0.13.4"
serde_json = "1.0"

[build-dependencies]
protobuf-codegen-pure = "2"
