[package]
name = "osm_extract_polygon"
version = "0.5.0"
authors = ["Andreas <andreas.gemsa@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.34.0"
geojson = { version =  "0.22.4", features=["geo-types"] }
geo-types = "0.7.6"
osmpbfreader = "0.15.2"
serde_json = "1.0.85"
smartstring = { version = "0.2.10", features = ["proptest", "serde"] }

[build-dependencies]
protobuf-codegen-pure = "2"
