[package]
name = "OsmToPolygon"
version = "0.1.0"
authors = ["Andreas <andreas.gemsa@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbfreader = "0.12.0"

[build-dependencies]
protobuf-codegen-pure = "2"
