name: Build and upload binaries to release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: osm_extract_polygon
            asset_name: osm_extract_polygon-linux-amd64
          - os: macos-latest
            artifact_name: osm_extract_polygon
            asset_name: osm_extract_polygon-macos-amd64
          - os: windows-latest
            artifact_name: osm_extract_polygon.exe
            asset_name: osm_extract_polygon-windows-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: prepare release
        run: |
          strip target/release/${{ matrix.artifact_name }}
          mkdir ${{ matrix.asset_name }}
          cp target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}/
          cp README.md ${{ matrix.asset_name }}/
          cp LICENSE ${{ matrix.asset_name }}/
          tar czvf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}